<a href="https://colab.research.google.com/github/Sneha1b/CSC-510-SE/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Loading the kaggle dataset into google collab
! pip install kaggle
! mkdir ~/.kaggle
! cp sample_data/kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets download mostafaabla/garbage-classification
! unzip garbage-classification

In [ ]:
# Loading the dataset into memory
import os
import glob
from skimage import io
import numpy as np
import random
from skimage.transform import resize

DATASET_PATH = '/content/garbage_classification/'

garbage_cls = ['battery', 'biological','brown-glass', 'cardboard','clothes','green-glass','metal','paper','plastic','shoes','trash','white-glass']

data = []
labels = []
cnt = 0
image_size = (150,150)
data_final = np.empty((150*150,3), dtype=float)
for cls in garbage_cls:
  data = []
  class_count = 0
  garbage_path = os.path.join(DATASET_PATH, cls, '*')
  garbage_path = glob.glob(garbage_path)
  for path in garbage_path:
    image = resize(io.imread(path), image_size)
    if(len(image.shape) <= 2):
      print("lost")
      continue
    class_count += 1
    image = np.linalg.norm(np.reshape(image, (150*150,3)))
    data.append(image)
    labels.append(cnt)
    if(class_count == 700 or (cls == 'battery' and class_count == 650)):
      break
  np.append(data_final, np.asarray(data))
  print("Class count for", cls, class_count)
  cnt += 1

labels = np.asarray(labels)
temp = list(zip(data_final, labels))
random.shuffle(temp)
data_final, labels = zip(*temp)


In [33]:
# Creating labels
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf

classes = []
numClasses = 12

label_encoder = LabelEncoder()
classes = label_encoder.fit_transform(garbage_cls)
classes = tf.keras.utils.to_categorical(classes, num_classes=numClasses)
classes = tf.constant(classes, shape=[numClasses, numClasses])

In [34]:
from sklearn.model_selection import train_test_split

#splitting to train and test
X_train, X_test, y_train, y_test = train_test_split(data_final, labels, test_size=0.2, random_state=1)

#splitting to train and validation
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.125, random_state=1)

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, random_state = 1)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=1)

In [36]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = rf.predict(X_val)

print ("Confusion Report")
print(confusion_matrix(y_val, y_val_pred))

y_val_pred=rf.predict(X_val)
print("validation accuracy:",metrics.accuracy_score(y_val_pred,y_val))

y_test_pred=rf.predict(X_test)
print("testing accuracy:",metrics.accuracy_score(y_test,y_test_pred))

Confusion Report
[[40 13  3  4  2  0  4  2  0  2  0  1]
 [12 20 10  8  6  4  2  3  3  4  0  0]
 [ 4 14 22  5  3  1  4  4  1  1  1  2]
 [ 6  7 10 28 10  1  2  0  3  1  1  4]
 [ 0  1  4 21 24 12  6  3  6  3  0  2]
 [ 1  2  0  4 11 17 17  0  2  3  0  3]
 [ 2  2  3  3  2 12 17  5  5  3  2  1]
 [ 1  2  6  2  3  3  9 27  8  7  1  2]
 [ 3  4  5  1  3  2  6  6 28  4  3  2]
 [ 1  3  2  3  0  1  5  5  4 24 12 10]
 [ 2  2  2  3  1  1  4  2  3 17 18  6]
 [ 2  2  0  1  1  0  4  1  1  8 19 31]]
validation accuracy: 0.3627450980392157
testing accuracy: 0.37193627450980393


In [49]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100, max_depth=25, random_state = 1)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=25, random_state=1)

In [50]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = rf.predict(X_val)

print ("Confusion Report")
print(confusion_matrix(y_val, y_val_pred))

y_val_pred=rf.predict(X_val)
print("validation accuracy:",metrics.accuracy_score(y_val_pred,y_val))

y_test_pred=rf.predict(X_test)
print("testing accuracy:",metrics.accuracy_score(y_test,y_test_pred))

Confusion Report
[[43 14  4  3  1  0  1  1  1  2  0  1]
 [12 20 10  8  6  4  2  4  3  3  0  0]
 [ 3 16 22  5  3  1  4  3  1  1  1  2]
 [ 5  6 12 30 10  0  3  0  2  1  1  3]
 [ 0  1  3 23 23 13  6  2  4  4  1  2]
 [ 1  2  1  3 11 19 17  1  2  2  0  1]
 [ 2  2  2  4  2 12 17  6  3  3  1  3]
 [ 1  2  7  1  2  3 10 27  8  8  0  2]
 [ 3  3  6  0  2  2  5  8 29  5  2  2]
 [ 3  2  2  4  0  0  3  4  4 27 11 10]
 [ 3  1  3  3  1  1  3  2  3 15 17  9]
 [ 3  2  0  1  0  0  4  2  1  8 18 31]]
validation accuracy: 0.3737745098039216
testing accuracy: 0.3786764705882353


In [39]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 500, random_state = 1)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=500, random_state=1)

In [40]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = rf.predict(X_val)

print ("Confusion Report")
print(confusion_matrix(y_val, y_val_pred))

y_val_pred=rf.predict(X_val)
print("validation accuracy:",metrics.accuracy_score(y_val_pred,y_val))

y_test_pred=rf.predict(X_test)
print("testing accuracy:",metrics.accuracy_score(y_test,y_test_pred))

Confusion Report
[[44 14  3  3  1  0  1  2  0  2  0  1]
 [13 21 11  7  6  4  0  3  3  4  0  0]
 [ 2 15 22  4  3  1  4  3  2  1  2  3]
 [ 4  6  9 32 11  1  2  0  3  1  1  3]
 [ 0  1  3 23 21 17  5  2  4  3  1  2]
 [ 1  2  0  4 11 18 18  1  1  2  0  2]
 [ 2  2  1  4  2 12 17  6  3  5  1  2]
 [ 0  3  7  2  2  3  9 26  5 11  0  3]
 [ 3  3  6  1  2  2  5  7 30  3  2  3]
 [ 3  3  2  3  1  1  3  4  5 25 10 10]
 [ 4  1  2  3  1  1  4  2  2 16 16  9]
 [ 2  2  0  1  0  1  3  1  1  8 17 34]]
validation accuracy: 0.375
testing accuracy: 0.3762254901960784


In [51]:
rf = RandomForestClassifier(n_estimators = 1000,max_depth=25,random_state=1)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=25, n_estimators=1000, random_state=1)

In [52]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = rf.predict(X_val)

print ("Confusion Report")
print(confusion_matrix(y_val, y_val_pred))

y_val_pred=rf.predict(X_val)
print("validation accuracy:",metrics.accuracy_score(y_val_pred,y_val))

y_test_pred=rf.predict(X_test)
print("testing accuracy:",metrics.accuracy_score(y_test,y_test_pred))

Confusion Report
[[42 14  3  4  1  0  2  1  1  2  0  1]
 [12 20 11  8  6  4  2  3  3  3  0  0]
 [ 3 15 21  4  4  1  3  3  2  1  2  3]
 [ 5  5  9 32 10  1  3  0  2  1  1  4]
 [ 0  1  3 21 23 16  5  2  5  4  0  2]
 [ 1  2  0  4  9 19 18  1  1  3  0  2]
 [ 2  2  1  4  2 12 16  6  3  5  1  3]
 [ 1  2  8  2  2  3  9 26  4 11  1  2]
 [ 3  3  6  1  2  2  6  6 30  4  2  2]
 [ 2  2  2  3  1  0  5  4  5 26 10 10]
 [ 3  2  3  3  2  1  3  2  2 17 15  8]
 [ 2  2  0  1  0  1  3  1  1  8 18 33]]
validation accuracy: 0.3713235294117647
testing accuracy: 0.37683823529411764


In [53]:
rf = RandomForestClassifier(n_estimators = 750,max_depth=25,max_features='sqrt',random_state=1)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=25, max_features='sqrt', n_estimators=750,
                       random_state=1)

In [54]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = rf.predict(X_val)

print ("Confusion Report")
print(confusion_matrix(y_val, y_val_pred))

y_val_pred=rf.predict(X_val)
print("validation accuracy:",metrics.accuracy_score(y_val_pred,y_val))

y_test_pred=rf.predict(X_test)
print("testing accuracy:",metrics.accuracy_score(y_test,y_test_pred))

Confusion Report
[[42 14  3  4  1  0  2  1  1  2  0  1]
 [13 20 11  8  6  4  1  3  3  3  0  0]
 [ 2 16 22  4  4  1  3  3  2  1  1  3]
 [ 4  5  9 32 11  1  2  0  3  1  1  4]
 [ 0  1  3 23 22 15  5  2  4  4  1  2]
 [ 1  2  0  4 10 19 18  1  1  2  0  2]
 [ 2  2  1  4  2 12 16  6  3  5  1  3]
 [ 1  2  8  2  2  3  9 26  4 11  1  2]
 [ 3  3  6  1  2  2  6  6 30  4  2  2]
 [ 2  2  2  3  1  0  5  4  5 26 10 10]
 [ 3  2  2  3  1  1  4  2  2 17 16  8]
 [ 2  2  0  1  0  0  3  2  1  8 18 33]]
validation accuracy: 0.37254901960784315
testing accuracy: 0.3756127450980392


In [55]:
rf = RandomForestClassifier(n_estimators = 750,max_depth=25,max_features='log2',random_state=1)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=25, max_features='log2', n_estimators=750,
                       random_state=1)

In [56]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = rf.predict(X_val)

print ("Confusion Report")
print(confusion_matrix(y_val, y_val_pred))

y_val_pred=rf.predict(X_val)
print("validation accuracy:",metrics.accuracy_score(y_val_pred,y_val))

y_test_pred=rf.predict(X_test)
print("testing accuracy:",metrics.accuracy_score(y_test,y_test_pred))

Confusion Report
[[42 14  3  4  1  0  2  1  1  2  0  1]
 [13 20 11  8  6  4  1  3  3  3  0  0]
 [ 2 16 22  4  4  1  3  3  2  1  1  3]
 [ 4  5  9 32 11  1  2  0  3  1  1  4]
 [ 0  1  3 23 22 15  5  2  4  4  1  2]
 [ 1  2  0  4 10 19 18  1  1  2  0  2]
 [ 2  2  1  4  2 12 16  6  3  5  1  3]
 [ 1  2  8  2  2  3  9 26  4 11  1  2]
 [ 3  3  6  1  2  2  6  6 30  4  2  2]
 [ 2  2  2  3  1  0  5  4  5 26 10 10]
 [ 3  2  2  3  1  1  4  2  2 17 16  8]
 [ 2  2  0  1  0  0  3  2  1  8 18 33]]
validation accuracy: 0.37254901960784315
testing accuracy: 0.3756127450980392
